import Head from 'next/head'
import {
    Grid,
    Badge,
    Button,
    Center,
    Flex,
    Heading,
    Image,
    Link,
    Stack,
    Text,
    useColorModeValue, Table,
    Thead,
    Tbody,
    Tfoot,
    Tr,
    Th,
    Td,
    TableCaption,
    TableContainer,
} from '@chakra-ui/react';
import Nav from '../../components/Navigation'
import ProductSimple from '../../components/Cards'

const IMAGE =
    'https://images.unsplash.com/photo-1518051870910-a46e30d9db16?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1350&q=80';

export async function getStaticPaths() {
    return {
        paths: [],
        fallback: true,
    }
}
export const products = [
    {
        id: "1",
        title: "react tshirt",
        category: "category",
        imageSrc: "https://picsum.photos/seed/picsum6/420/260",
        price: "$23.00"
    },
    {
        id: "2",
        title: "chakraUI mug",
        category: "category",
        imageSrc: "https://picsum.photos/seed/picsum5/421/261",
        price: "$15.00"
    },
    {
        id: "3",
        title: "black tshirt",
        category: "category",
        imageSrc: "https://picsum.photos/seed/picsum4/422/262",
        price: "$10.25"
    }
];
export async function getStaticProps({ params }) {
    let data = {
        id: "1",
        title: "react tshirt",
        category: "category",
        imageSrc: "https://picsum.photos/seed/picsum6/420/260",
        price: "$23.00"
    }

    return {
        props: {
            id: "1",
            title: "react tshirt",
            category: "category",
            imageSrc: "https://picsum.photos/seed/picsum6/420/260",
            price: "$23.00"
        },
        revalidate: 1,
    }
}

export default function ProductDetail({ id, title, category, imageSrc, price }) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Nav />
                <Center py={1}>
                    <Stack
                        borderWidth="1px"
                        borderRadius="lg"
                        w={{ sm: '100%', md: '70rem' }}
                        height={{ sm: '700px', md: '40rem' }}
                        direction={{ base: 'column', md: 'row' }}
                        bg={useColorModeValue('white', 'gray.900')}
                        boxShadow={'2xl'}
                        padding={1}>
                        <Flex flex={1} bg="blue.200">
                            <Image
                                objectFit="cover"
                                boxSize="100%"
                                src={
                                    'https://down-vn.img.susercontent.com/file/81db3aec45e555ada18535a4f2383b88'
                                }
                            />
                        </Flex>
                        <Stack
                            flex={1}
                            flexDirection="column"
                            //   justifyContent="center"
                            //   alignItems="center"
                            p={1}
                            pt={2}>
                            <Heading fontSize={'2xl'} fontFamily={'body'}>
                                Tee basic ss1 CREWZ áo thun tay lỡ unisex Local Brand - AO_THUN_DVR (V427)
                            </Heading>
                            <Text fontWeight={600} color={'gray.500'} size="sm" mb={4}>
                                ₫79.000
                            </Text>
                            <Text
                                textAlign={'left'}
                                color={useColorModeValue('gray.700', 'gray.400')}
                                px={3}>
                                MÔ TẢ SẢN PHẨM
                                - Áo thun nam nữ oversize sử dụng chất vải cotton 65/35 co giãn 4 chiều. Là loại vải có đặc điểm mềm mịn, độ co giãn cao, khả năng thấm hút tốt và được dệt hoàn toàn từ sợi cây bông tự nhiên. Chất vải cotton cực kỳ thân thiện với làn da.
                                - Áo thun nam nữ form rộng cổ tròn thoải mái
                                - Áo phông unisex form rộng dễ phối đồ. Bạn có thể phối với quần jean, chân váy, … kết hợp với một đôi sneaker cho bạn tự tin xuống phố
                                <Link href={'#'} color={'blue.400'}>
                                    #tag
                                </Link>
                                me in your posts
                            </Text>
                            <Stack align={'center'} justify={'center'} direction={'row'} mt={6}>
                                <Badge
                                    px={2}
                                    py={1}
                                    bg={useColorModeValue('gray.50', 'gray.800')}
                                    fontWeight={'400'}>
                                    #art
                                </Badge>
                                <Badge
                                    px={2}
                                    py={1}
                                    bg={useColorModeValue('gray.50', 'gray.800')}
                                    fontWeight={'400'}>
                                    #photography
                                </Badge>
                                <Badge
                                    px={2}
                                    py={1}
                                    bg={useColorModeValue('gray.50', 'gray.800')}
                                    fontWeight={'400'}>
                                    #music
                                </Badge>
                            </Stack>

                            <TableContainer>
                                <Table variant='simple'>
                                    <TableCaption>Imperial to metric conversion factors</TableCaption>
                                    <Thead>
                                        <Tr>
                                            <Th>To convert</Th>
                                            <Th>into</Th>
                                            <Th isNumeric>multiply by</Th>
                                        </Tr>
                                    </Thead>
                                    <Tbody>
                                        <Tr>
                                            <Td>inches</Td>
                                            <Td>millimetres (mm)</Td>
                                            <Td isNumeric>25.4</Td>
                                        </Tr>
                                        <Tr>
                                            <Td>feet</Td>
                                            <Td>centimetres (cm)</Td>
                                            <Td isNumeric>30.48</Td>
                                        </Tr>
                                        <Tr>
                                            <Td>yards</Td>
                                            <Td>metres (m)</Td>
                                            <Td isNumeric>0.91444</Td>
                                        </Tr>
                                    </Tbody>
                                    <Tfoot>
                                        <Tr>
                                            <Th>To convert</Th>
                                            <Th>into</Th>
                                            <Th isNumeric>multiply by</Th>
                                        </Tr>
                                    </Tfoot>
                                </Table>
                            </TableContainer>
                            <Stack direction='row' spacing={4}>
                                <Button colorScheme='pink' variant='solid'>
                                    Settings
                                </Button>
                                <Button colorScheme='blue' variant='outline'>
                                    Call us
                                </Button>
                            </Stack>
                        </Stack>
                    </Stack>
                </Center>
                <Center bg='tomato' h='100px' color='white'>
                    This is the Center
                </Center>
                <Flex
                    direction="column"
                    // justifyContent="center"
                    py={4}
                    maxW={{ xl: "1200px" }}
                    m="0 auto"
                    minH="100vh"
                >
                    <Grid
                        w="full"
                        gridGap="5"
                        gridTemplateColumns="repeat( auto-fit, minmax(300px, 1fr) )"
                    >
                        {products.map((p) => (
                            <ProductSimple key={p.id} {...p} />
                        ))}
                    </Grid>
                </Flex>
            </main>
        </>
    )
}