import Head from 'next/head'
import { Flex, Container, Grid, GridItem, SimpleGrid } from '@chakra-ui/react'
import ProductSimple from '../components/Cards'
import Nav from '../components/Navigation'
export const products = [
  {
    id: "1",
    title: "react tshirt",
    category: "category",
    imageSrc: "https://picsum.photos/seed/picsum6/420/260",
    price: "$23.00"
  },
  {
    id: "2",
    title: "chakraUI mug",
    category: "category",
    imageSrc: "https://picsum.photos/seed/picsum5/421/261",
    price: "$15.00"
  },
  {
    id: "3",
    title: "black tshirt",
    category: "category",
    imageSrc: "https://picsum.photos/seed/picsum4/422/262",
    price: "$10.25"
  },
  {
    id: "4",
    title: "react tshirt",
    category: "category",
    imageSrc: "https://picsum.photos/seed/picsum3/420/260",
    price: "$23.00"
  },
  {
    id: "5",
    title: "chakraUI mug",
    category: "category",
    imageSrc: "https://picsum.photos/seed/picsum2/421/261",
    price: "$15.00"
  },
  {
    id: "6",
    title: "black tshirt",
    category: "category",
    imageSrc: "https://picsum.photos/seed/picsum1/422/262",
    price: "$10.25"
  }
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ backgroundColor: 'white' }}>
        <Flex
          direction="column"
          justifyContent="center"
          maxW={{ xl: "1200px" }}
          m="0 auto"
          minH="100vh"
        >
          <Grid
            w="full"
            gridGap="5"
            gridTemplateColumns="repeat( auto-fit, minmax(300px, 1fr) )"
          >
            {products.map((p) => (
              <ProductSimple key={p.id} {...p} />
            ))}
          </Grid>
        </Flex>
      </main>
    </>
  )
}
